# Generated by Django 5.2.5 on 2025-08-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_rename_users_doctor_remove_appointment_doctor_and_more'),
        ('clicnic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='care.doctor'),
        ),
    ]
