# Generated by Django 5.2.5 on 2025-08-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicnic', '0002_hospital_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='pincode',
            field=models.CharField(max_length=7),
        ),
    ]
